In [1]:
import numpy as np

In [2]:
s = 5

In [3]:
s

5

In [4]:
v = np.array([5,-2,4])

In [5]:
v

array([ 5, -2,  4])

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array(5)

In [12]:
type(s_array)

numpy.ndarray

In [13]:
s_array

array(5)

In [14]:
m.shape

(2, 3)

In [15]:
v.shape

(3,)

In [16]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [17]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [18]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [19]:
s_array.shape

()

In [21]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [22]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [24]:
t = np.array([m1,m2])

In [25]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [26]:
t.shape

(2, 2, 3)